### PR TITLE
adds publisher, tags, and article level notes to metadata section

### PR DESCRIPTION
**Pull request by hunterclarke**

### CODE REVIEW

**Comment by thorms11** [comment]
hey @hunterclarke, i am not seeing article level notes in the meta data.

**Comment by hunterclarke** [comment]
@thorms11 could you verify you are running version 1.0.7?

**Comment by thorms11** [comment]
Yes, I can verify that I am running 1.0.7
image

image

image

**Comment by hunterclarke** [comment]
Thanks for the thorough response! Did you sync this note before or after upgrading? If the note was created before upgrading to 1.0.7, then you'll need to delete it and re-sync it in order for the article level note to show up.

**Comment by hunterclarke** [comment]
Sorry I realize that was ambiguous. If the _Obsidian_ file was created before 1.0.7, you'll need to delete the file from your vault, and initialize another sync with Matter.

I couldn't shim the article level notes in without possibly corrupting user edits within already created files.

**Comment by thorms11** [comment]
Yes! That solves it. Thank you. 

Do you generally post release notes?

**Comment by thorms11** [comment]
Hey Hunter! I am seeing notes that are made at the highlight-level sync consistently, but not notes at the article-level. 

Highlight-level: 
image

Article-level: 
image


Deleting and resyncing fixes the issue, but this can be a pain if there are already notes or external links in Obsidian. 

Seems like it happens if Obsidian syncs before the article is archived in Matter. 

Steps to repro: 
1. add article to matter
2. make highlights, etc. 
3. launch Obsidian
4. let matter sync successfully
5. check the note for accuracy 
6. in matter, make a note on the top of the notebook
7. archive the article
8. in obsidian, re-sync
9. article level note will likely not show
10. delete the obsidian note
11. re-sync
12. it should now show

Let me know if you have any other questions.

**Comment by hunterclarke** [comment]
@thorms11 yeah this is kind of a balancing act. In other integrations (Readwise and Notion) we actually put a delay in that prevents the entries from being created if they are too fresh (created within the last 10 minutes) to prevent this kind of problem. However, then we get reports of sync not working or delayed. If you're seeing this issue pop up a lot, I'd recommend extending your sync frequency to try and batch more complete records (or disable it entirely and use the manual sync command)

I'd like to figure out a way that we can shim the article level note in the already created note. However, I'm going to delay that project until after [templates](https://github.com/getmatterapp/obsidian-matter/issues/4) (coming soon). Any work done on templates would impact the parsing and shimming implementation I decide on.

I appreciate the thorough reports!

**Pull request merged**
